"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "novu-py"
__version__: str = "3.13.0"
__openapi_doc_version__: str = "3.12.0"
__gen_version__: str = "2.801.2"
__user_agent__: str = "speakeasy-sdk/python 3.13.0 2.801.2 3.12.0 novu-py"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
