"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .executiondetailssourceenum import ExecutionDetailsSourceEnum
from .executiondetailsstatusenum import ExecutionDetailsStatusEnum
from .providersidenum import ProvidersIDEnum
from novu_py.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ActivityNotificationExecutionDetailResponseDtoTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the execution detail"""
    status: ExecutionDetailsStatusEnum
    r"""Status of the execution detail"""
    detail: str
    r"""Detailed information about the execution"""
    is_retry: bool
    r"""Whether the execution is a retry or not"""
    is_test: bool
    r"""Whether the execution is a test or not"""
    source: ExecutionDetailsSourceEnum
    r"""Source of the execution detail"""
    created_at: NotRequired[str]
    r"""Creation time of the execution detail"""
    provider_id: NotRequired[ProvidersIDEnum]
    r"""Provider ID of the job"""
    raw: NotRequired[Nullable[str]]
    r"""Raw data of the execution"""


class ActivityNotificationExecutionDetailResponseDto(BaseModel):
    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""Unique identifier of the execution detail"""

    status: ExecutionDetailsStatusEnum
    r"""Status of the execution detail"""

    detail: str
    r"""Detailed information about the execution"""

    is_retry: Annotated[bool, pydantic.Field(alias="isRetry")]
    r"""Whether the execution is a retry or not"""

    is_test: Annotated[bool, pydantic.Field(alias="isTest")]
    r"""Whether the execution is a test or not"""

    source: ExecutionDetailsSourceEnum
    r"""Source of the execution detail"""

    created_at: Annotated[Optional[str], pydantic.Field(alias="createdAt")] = None
    r"""Creation time of the execution detail"""

    provider_id: Annotated[
        Optional[ProvidersIDEnum], pydantic.Field(alias="providerId")
    ] = None
    r"""Provider ID of the job"""

    raw: OptionalNullable[str] = UNSET
    r"""Raw data of the execution"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["createdAt", "providerId", "raw"])
        nullable_fields = set(["raw"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
