"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentToolDtoType(str, Enum):
    BUILTIN = "builtin"
    CUSTOM = "custom"


class AgentToolDtoTypedDict(TypedDict):
    external_id: str
    name: str
    type: AgentToolDtoType
    description: NotRequired[str]


class AgentToolDto(BaseModel):
    external_id: Annotated[str, pydantic.Field(alias="externalId")]

    name: str

    type: AgentToolDtoType

    description: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AgentToolDto.model_rebuild()
except NameError:
    pass
