"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentSkillInputDtoType(str, Enum):
    ANTHROPIC = "anthropic"
    CUSTOM = "custom"


class VersionTypedDict(TypedDict):
    r"""Version to pin. Omit for latest."""


class Version(BaseModel):
    r"""Version to pin. Omit for latest."""


class AgentSkillInputDtoTypedDict(TypedDict):
    type: AgentSkillInputDtoType
    skill_id: str
    r"""Skill identifier, e.g. \"xlsx\" or \"skill_01XJ5...\" """
    version: NotRequired[Nullable[VersionTypedDict]]
    r"""Version to pin. Omit for latest."""


class AgentSkillInputDto(BaseModel):
    type: AgentSkillInputDtoType

    skill_id: Annotated[str, pydantic.Field(alias="skillId")]
    r"""Skill identifier, e.g. \"xlsx\" or \"skill_01XJ5...\" """

    version: OptionalNullable[Version] = UNSET
    r"""Version to pin. Omit for latest."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["version"])
        nullable_fields = set(["version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AgentSkillInputDto.model_rebuild()
except NameError:
    pass
