"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class LimitSource(str, Enum):
    r"""Which constraint produced the limits. `plan` limits are lifted by upgrading; `system` limits (platform cap or per-organization override) require contacting the Novu team."""

    PLAN = "plan"
    SYSTEM = "system"


class AgentPlanUsageDtoTypedDict(TypedDict):
    used: float
    r"""Current usage count for the resource in this environment."""
    limit: float
    r"""Amount included in the organization plan."""
    total_created: float
    r"""Total agents in this environment, including inactive ones."""
    creation_limit: float
    r"""Hard cap on total agents the organization can create per environment. For plan-limited tiers this is the plan limit plus a small grace buffer; for unlimited tiers it is the platform system limit."""
    limit_source: LimitSource
    r"""Which constraint produced the limits. `plan` limits are lifted by upgrading; `system` limits (platform cap or per-organization override) require contacting the Novu team."""


class AgentPlanUsageDto(BaseModel):
    used: float
    r"""Current usage count for the resource in this environment."""

    limit: float
    r"""Amount included in the organization plan."""

    total_created: Annotated[float, pydantic.Field(alias="totalCreated")]
    r"""Total agents in this environment, including inactive ones."""

    creation_limit: Annotated[float, pydantic.Field(alias="creationLimit")]
    r"""Hard cap on total agents the organization can create per environment. For plan-limited tiers this is the plan limit plus a small grace buffer; for unlimited tiers it is the platform system limit."""

    limit_source: Annotated[LimitSource, pydantic.Field(alias="limitSource")]
    r"""Which constraint produced the limits. `plan` limits are lifted by upgrading; `system` limits (platform cap or per-organization override) require contacting the Novu team."""


try:
    AgentPlanUsageDto.model_rebuild()
except NameError:
    pass
