"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthDtoTypedDict(TypedDict):
    access_token: str
    refresh_token: NotRequired[str]
    expires_at: NotRequired[str]
    refresh_token_expires_at: NotRequired[str]


class AuthDto(BaseModel):
    access_token: Annotated[str, pydantic.Field(alias="accessToken")]

    refresh_token: Annotated[Optional[str], pydantic.Field(alias="refreshToken")] = None

    expires_at: Annotated[Optional[str], pydantic.Field(alias="expiresAt")] = None

    refresh_token_expires_at: Annotated[
        Optional[str], pydantic.Field(alias="refreshTokenExpiresAt")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["refreshToken", "expiresAt", "refreshTokenExpiresAt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthDto.model_rebuild()
except NameError:
    pass
