"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class ChatRenderOutputTypedDict(TypedDict):
    body: NotRequired[str]
    r"""Body of the chat message. Mutually exclusive with `card`."""
    card: NotRequired[Dict[str, Any]]
    r"""Rich Chat: compiled provider-agnostic card DSL. Mutually exclusive with `body`."""


class ChatRenderOutput(BaseModel):
    body: Optional[str] = None
    r"""Body of the chat message. Mutually exclusive with `card`."""

    card: Optional[Dict[str, Any]] = None
    r"""Rich Chat: compiled provider-agnostic card DSL. Mutually exclusive with `body`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body", "card"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
