"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .credentialsdto import CredentialsDto, CredentialsDtoTypedDict
from .stepfilterdto import StepFilterDto, StepFilterDtoTypedDict
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateIntegrationRequestDtoChannel(str, Enum):
    r"""The channel type for the integration. Not required for agent-kind integrations."""

    IN_APP = "in_app"
    EMAIL = "email"
    SMS = "sms"
    CHAT = "chat"
    PUSH = "push"
    TOOL = "tool"


class CreateIntegrationRequestDtoKind(str, Enum):
    r"""Distinguishes delivery integrations from agent-runtime integrations. Defaults to \"delivery\". Agent integrations do not require a channel."""

    DELIVERY = "delivery"
    AGENT = "agent"


class ConfigurationsTypedDict(TypedDict):
    r"""Configurations for the integration"""


class Configurations(BaseModel):
    r"""Configurations for the integration"""


class CreateIntegrationRequestDtoTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the integration"""
    identifier: NotRequired[str]
    r"""The unique identifier for the integration"""
    environment_id: NotRequired[str]
    r"""The ID of the associated environment"""
    provider_id: NotRequired[str]
    r"""The provider ID for the integration"""
    channel: NotRequired[CreateIntegrationRequestDtoChannel]
    r"""The channel type for the integration. Not required for agent-kind integrations."""
    kind: NotRequired[CreateIntegrationRequestDtoKind]
    r"""Distinguishes delivery integrations from agent-runtime integrations. Defaults to \"delivery\". Agent integrations do not require a channel."""
    credentials: NotRequired[CredentialsDtoTypedDict]
    r"""The credentials for the integration"""
    active: NotRequired[bool]
    r"""If the integration is active, the validation on the credentials field will run"""
    check: NotRequired[bool]
    r"""Flag to check the integration status"""
    conditions: NotRequired[List[StepFilterDtoTypedDict]]
    r"""Conditions for the integration"""
    configurations: NotRequired[ConfigurationsTypedDict]
    r"""Configurations for the integration"""


class CreateIntegrationRequestDto(BaseModel):
    name: Optional[str] = None
    r"""The name of the integration"""

    identifier: Optional[str] = None
    r"""The unique identifier for the integration"""

    environment_id: Annotated[Optional[str], pydantic.Field(alias="_environmentId")] = (
        None
    )
    r"""The ID of the associated environment"""

    provider_id: Annotated[Optional[str], pydantic.Field(alias="providerId")] = None
    r"""The provider ID for the integration"""

    channel: Optional[CreateIntegrationRequestDtoChannel] = None
    r"""The channel type for the integration. Not required for agent-kind integrations."""

    kind: Optional[CreateIntegrationRequestDtoKind] = None
    r"""Distinguishes delivery integrations from agent-runtime integrations. Defaults to \"delivery\". Agent integrations do not require a channel."""

    credentials: Optional[CredentialsDto] = None
    r"""The credentials for the integration"""

    active: Optional[bool] = None
    r"""If the integration is active, the validation on the credentials field will run"""

    check: Optional[bool] = None
    r"""Flag to check the integration status"""

    conditions: Optional[List[StepFilterDto]] = None
    r"""Conditions for the integration"""

    configurations: Optional[Configurations] = None
    r"""Configurations for the integration"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "identifier",
                "_environmentId",
                "providerId",
                "channel",
                "kind",
                "credentials",
                "active",
                "check",
                "conditions",
                "configurations",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateIntegrationRequestDto.model_rebuild()
except NameError:
    pass
