"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pagerdutyserviceendpointdto import (
    PagerDutyServiceEndpointDto,
    PagerDutyServiceEndpointDtoTypedDict,
)
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class CreatePagerDutyServiceEndpointDtoContext2TypedDict(TypedDict):
    r"""Rich context object with id and optional data"""

    id: str
    data: NotRequired[Dict[str, Any]]
    r"""Optional additional context data"""


class CreatePagerDutyServiceEndpointDtoContext2(BaseModel):
    r"""Rich context object with id and optional data"""

    id: str

    data: Optional[Dict[str, Any]] = None
    r"""Optional additional context data"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


CreatePagerDutyServiceEndpointDtoContextTypedDict = TypeAliasType(
    "CreatePagerDutyServiceEndpointDtoContextTypedDict",
    Union[CreatePagerDutyServiceEndpointDtoContext2TypedDict, str],
)


CreatePagerDutyServiceEndpointDtoContext = TypeAliasType(
    "CreatePagerDutyServiceEndpointDtoContext",
    Union[CreatePagerDutyServiceEndpointDtoContext2, str],
)


class CreatePagerDutyServiceEndpointDtoType(str, Enum):
    r"""Type of channel endpoint"""

    PAGERDUTY_SERVICE = "pagerduty_service"


class CreatePagerDutyServiceEndpointDtoTypedDict(TypedDict):
    subscriber_id: str
    r"""The subscriber ID to which the channel endpoint is linked"""
    integration_identifier: str
    r"""The identifier of the integration to use for this channel endpoint."""
    type: CreatePagerDutyServiceEndpointDtoType
    r"""Type of channel endpoint"""
    endpoint: PagerDutyServiceEndpointDtoTypedDict
    r"""PagerDuty service endpoint data. `routingKey` is encrypted at rest on the channel endpoint (`endpoint` field); `region` remains plaintext. No linked channel connection."""
    identifier: NotRequired[str]
    r"""The unique identifier for the channel endpoint. If not provided, one will be generated automatically."""
    create_subscriber_if_missing: NotRequired[bool]
    r"""When true, the subscriber is created if it does not exist yet (existing subscribers are never modified). When false or omitted, an unknown subscriberId returns 404."""
    context: NotRequired[Dict[str, CreatePagerDutyServiceEndpointDtoContextTypedDict]]
    connection_identifier: NotRequired[str]
    r"""The identifier of the channel connection to use for this channel endpoint."""


class CreatePagerDutyServiceEndpointDto(BaseModel):
    subscriber_id: Annotated[str, pydantic.Field(alias="subscriberId")]
    r"""The subscriber ID to which the channel endpoint is linked"""

    integration_identifier: Annotated[
        str, pydantic.Field(alias="integrationIdentifier")
    ]
    r"""The identifier of the integration to use for this channel endpoint."""

    type: CreatePagerDutyServiceEndpointDtoType
    r"""Type of channel endpoint"""

    endpoint: PagerDutyServiceEndpointDto
    r"""PagerDuty service endpoint data. `routingKey` is encrypted at rest on the channel endpoint (`endpoint` field); `region` remains plaintext. No linked channel connection."""

    identifier: Optional[str] = None
    r"""The unique identifier for the channel endpoint. If not provided, one will be generated automatically."""

    create_subscriber_if_missing: Annotated[
        Optional[bool], pydantic.Field(alias="createSubscriberIfMissing")
    ] = False
    r"""When true, the subscriber is created if it does not exist yet (existing subscribers are never modified). When false or omitted, an unknown subscriberId returns 404."""

    context: Optional[Dict[str, CreatePagerDutyServiceEndpointDtoContext]] = None

    connection_identifier: Annotated[
        Optional[str], pydantic.Field(alias="connectionIdentifier")
    ] = None
    r"""The identifier of the channel connection to use for this channel endpoint."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "identifier",
                "createSubscriberIfMissing",
                "context",
                "connectionIdentifier",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreatePagerDutyServiceEndpointDto.model_rebuild()
except NameError:
    pass
