"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class Code(str, Enum):
    MX_MISSING = "mx_missing"
    MX_WRONG_TARGET = "mx_wrong_target"
    MX_LOW_PRIORITY = "mx_low_priority"
    APEX_CNAME_COLLISION = "apex_cname_collision"
    DNSBL_LISTED = "dnsbl_listed"


class DomainDiagnosticCheckDtoStatus(str, Enum):
    PASS = "pass"
    FAIL = "fail"
    SKIPPED = "skipped"


class DomainDiagnosticCheckDtoTypedDict(TypedDict):
    code: Code
    status: DomainDiagnosticCheckDtoStatus
    latency_ms: float
    r"""Round-trip time for this check in milliseconds"""


class DomainDiagnosticCheckDto(BaseModel):
    code: Code

    status: DomainDiagnosticCheckDtoStatus

    latency_ms: Annotated[float, pydantic.Field(alias="latencyMs")]
    r"""Round-trip time for this check in milliseconds"""


try:
    DomainDiagnosticCheckDto.model_rebuild()
except NameError:
    pass
