"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
from typing_extensions import TypedDict


class EmailRenderOutputTypedDict(TypedDict):
    subject: str
    r"""Subject of the email"""
    body: str
    r"""Body of the email"""


class EmailRenderOutput(BaseModel):
    subject: str
    r"""Subject of the email"""

    body: str
    r"""Body of the email"""
