"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .emailcontroldto import EmailControlDto, EmailControlDtoTypedDict
from .steptypeenum import StepTypeEnum
from novu_py.types import BaseModel
import pydantic
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


EmailStepUpsertDtoControlValuesTypedDict = TypeAliasType(
    "EmailStepUpsertDtoControlValuesTypedDict",
    Union[EmailControlDtoTypedDict, Dict[str, Any]],
)
r"""Control values for the Email step."""


EmailStepUpsertDtoControlValues = TypeAliasType(
    "EmailStepUpsertDtoControlValues", Union[EmailControlDto, Dict[str, Any]]
)
r"""Control values for the Email step."""


class EmailStepUpsertDtoTypedDict(TypedDict):
    name: str
    r"""Name of the step"""
    type: StepTypeEnum
    r"""Type of the step"""
    id: NotRequired[str]
    r"""Unique identifier of the step"""
    control_values: NotRequired[EmailStepUpsertDtoControlValuesTypedDict]
    r"""Control values for the Email step."""


class EmailStepUpsertDto(BaseModel):
    name: str
    r"""Name of the step"""

    type: StepTypeEnum
    r"""Type of the step"""

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = None
    r"""Unique identifier of the step"""

    control_values: Annotated[
        Optional[EmailStepUpsertDtoControlValues], pydantic.Field(alias="controlValues")
    ] = None
    r"""Control values for the Email step."""
