"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .getenvironmentvariableusageresponsedto import (
    GetEnvironmentVariableUsageResponseDto,
    GetEnvironmentVariableUsageResponseDtoTypedDict,
)
from novu_py.types import BaseModel, UNSET_SENTINEL
from novu_py.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EnvironmentVariablesControllerGetEnvironmentVariableUsageRequestTypedDict(
    TypedDict
):
    variable_key: str
    r"""The unique key of the environment variable (e.g. BASE_URL)"""
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class EnvironmentVariablesControllerGetEnvironmentVariableUsageRequest(BaseModel):
    variable_key: Annotated[
        str,
        pydantic.Field(alias="variableKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The unique key of the environment variable (e.g. BASE_URL)"""

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["idempotency-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EnvironmentVariablesControllerGetEnvironmentVariableUsageResponseTypedDict(
    TypedDict
):
    headers: Dict[str, List[str]]
    result: GetEnvironmentVariableUsageResponseDtoTypedDict


class EnvironmentVariablesControllerGetEnvironmentVariableUsageResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: GetEnvironmentVariableUsageResponseDto
