"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createenvironmentrequestdto import (
    CreateEnvironmentRequestDto,
    CreateEnvironmentRequestDtoTypedDict,
)
from .environmentresponsedto import (
    EnvironmentResponseDto,
    EnvironmentResponseDtoTypedDict,
)
from novu_py.types import BaseModel, UNSET_SENTINEL
from novu_py.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EnvironmentsControllerV1CreateEnvironmentRequestTypedDict(TypedDict):
    create_environment_request_dto: CreateEnvironmentRequestDtoTypedDict
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class EnvironmentsControllerV1CreateEnvironmentRequest(BaseModel):
    create_environment_request_dto: Annotated[
        CreateEnvironmentRequestDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["idempotency-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EnvironmentsControllerV1CreateEnvironmentResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: EnvironmentResponseDtoTypedDict


class EnvironmentsControllerV1CreateEnvironmentResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: EnvironmentResponseDto
