"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class EnvironmentVariableValueResponseDtoTypedDict(TypedDict):
    environment_id: str
    value: str
    r"""Value is masked (••••••••) for secret variables"""


class EnvironmentVariableValueResponseDto(BaseModel):
    environment_id: Annotated[str, pydantic.Field(alias="_environmentId")]

    value: str
    r"""Value is masked (••••••••) for secret variables"""


try:
    EnvironmentVariableValueResponseDto.model_rebuild()
except NameError:
    pass
