"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileRefDtoTypedDict(TypedDict):
    filename: str
    r"""Filename shown to the end user, including extension."""
    mime_type: NotRequired[str]
    r"""IANA MIME type of the file."""
    data: NotRequired[str]
    r"""Base64-encoded inline file bytes. Mutually exclusive with `url`. Decoded size must be ≤ 5 MB. Prefer `url` for larger files."""
    url: NotRequired[str]
    r"""Publicly accessible HTTP(S) URL. Mutually exclusive with `data`. Server-side limits: 25 MB per file, 15 files per message, 50 MB aggregate."""


class FileRefDto(BaseModel):
    filename: str
    r"""Filename shown to the end user, including extension."""

    mime_type: Annotated[Optional[str], pydantic.Field(alias="mimeType")] = None
    r"""IANA MIME type of the file."""

    data: Optional[str] = None
    r"""Base64-encoded inline file bytes. Mutually exclusive with `url`. Decoded size must be ≤ 5 MB. Prefer `url` for larger files."""

    url: Optional[str] = None
    r"""Publicly accessible HTTP(S) URL. Mutually exclusive with `data`. Server-side limits: 25 MB per file, 15 files per message, 50 MB aggregate."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mimeType", "data", "url"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    FileRefDto.model_rebuild()
except NameError:
    pass
