"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatrenderoutput import ChatRenderOutput, ChatRenderOutputTypedDict
from .digestregularoutput import DigestRegularOutput, DigestRegularOutputTypedDict
from .emailrenderoutput import EmailRenderOutput, EmailRenderOutputTypedDict
from .inapprenderoutput import InAppRenderOutput, InAppRenderOutputTypedDict
from .previewerrordto import PreviewErrorDto, PreviewErrorDtoTypedDict
from .previewpayloaddto import PreviewPayloadDto, PreviewPayloadDtoTypedDict
from .pushrenderoutput import PushRenderOutput, PushRenderOutputTypedDict
from .smsrenderoutput import SmsRenderOutput, SmsRenderOutputTypedDict
from enum import Enum
from novu_py.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GeneratePreviewResponseDtoResult9Type(str, Enum):
    DIGEST = "digest"


class NineTypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult9Type]
    preview: NotRequired[DigestRegularOutputTypedDict]


class Nine(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult9Type] = None

    preview: Optional[DigestRegularOutput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult8Type(str, Enum):
    DELAY = "delay"


class EightTypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult8Type]
    preview: NotRequired[DigestRegularOutputTypedDict]


class Eight(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult8Type] = None

    preview: Optional[DigestRegularOutput] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult7Type(str, Enum):
    CHAT = "chat"


class SevenTypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult7Type]
    preview: NotRequired[ChatRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Seven(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult7Type] = None

    preview: Optional[ChatRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult6Type(str, Enum):
    PUSH = "push"


class SixTypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult6Type]
    preview: NotRequired[PushRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Six(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult6Type] = None

    preview: Optional[PushRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult5Type(str, Enum):
    SMS = "sms"


class Result5TypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult5Type]
    preview: NotRequired[SmsRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Result5(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult5Type] = None

    preview: Optional[SmsRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult4Type(str, Enum):
    IN_APP = "in_app"


class Result4TypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult4Type]
    preview: NotRequired[InAppRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Result4(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult4Type] = None

    preview: Optional[InAppRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResult3Type(str, Enum):
    EMAIL = "email"


class ThreeTypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResult3Type]
    preview: NotRequired[EmailRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Three(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResult3Type] = None

    preview: Optional[EmailRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GeneratePreviewResponseDtoResultType(str, Enum):
    EMAIL = "email"


class Result2TypedDict(TypedDict):
    type: NotRequired[GeneratePreviewResponseDtoResultType]
    preview: NotRequired[EmailRenderOutputTypedDict]
    error: NotRequired[PreviewErrorDtoTypedDict]


class Result2(BaseModel):
    type: Optional[GeneratePreviewResponseDtoResultType] = None

    preview: Optional[EmailRenderOutput] = None

    error: Optional[PreviewErrorDto] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "preview", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GeneratePreviewResponseDtoResultTypedDict = TypeAliasType(
    "GeneratePreviewResponseDtoResultTypedDict",
    Union[
        EightTypedDict,
        NineTypedDict,
        Result2TypedDict,
        ThreeTypedDict,
        Result4TypedDict,
        Result5TypedDict,
        SixTypedDict,
        SevenTypedDict,
        Dict[str, Any],
    ],
)
r"""Preview result"""


GeneratePreviewResponseDtoResult = TypeAliasType(
    "GeneratePreviewResponseDtoResult",
    Union[Eight, Nine, Result2, Three, Result4, Result5, Six, Seven, Dict[str, Any]],
)
r"""Preview result"""


class GeneratePreviewResponseDtoTypedDict(TypedDict):
    preview_payload_example: PreviewPayloadDtoTypedDict
    r"""Preview payload example"""
    result: GeneratePreviewResponseDtoResultTypedDict
    r"""Preview result"""
    schema_: NotRequired[Nullable[Dict[str, Any]]]
    r"""The payload schema that was used to generate the preview payload example"""
    novu_signature: NotRequired[str]
    r"""Sample novu-signature header value for HTTP request steps"""


class GeneratePreviewResponseDto(BaseModel):
    preview_payload_example: Annotated[
        PreviewPayloadDto, pydantic.Field(alias="previewPayloadExample")
    ]
    r"""Preview payload example"""

    result: GeneratePreviewResponseDtoResult
    r"""Preview result"""

    schema_: Annotated[
        OptionalNullable[Dict[str, Any]], pydantic.Field(alias="schema")
    ] = UNSET
    r"""The payload schema that was used to generate the preview payload example"""

    novu_signature: Annotated[Optional[str], pydantic.Field(alias="novuSignature")] = (
        None
    )
    r"""Sample novu-signature header value for HTTP request steps"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["schema", "novuSignature"])
        nullable_fields = set(["schema"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GeneratePreviewResponseDto.model_rebuild()
except NameError:
    pass
