"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GenerateLinkUserOauthURLRequestDtoContext2TypedDict(TypedDict):
    r"""Rich context object with id and optional data"""

    id: str
    data: NotRequired[Dict[str, Any]]
    r"""Optional additional context data"""


class GenerateLinkUserOauthURLRequestDtoContext2(BaseModel):
    r"""Rich context object with id and optional data"""

    id: str

    data: Optional[Dict[str, Any]] = None
    r"""Optional additional context data"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GenerateLinkUserOauthURLRequestDtoContextTypedDict = TypeAliasType(
    "GenerateLinkUserOauthURLRequestDtoContextTypedDict",
    Union[GenerateLinkUserOauthURLRequestDtoContext2TypedDict, str],
)


GenerateLinkUserOauthURLRequestDtoContext = TypeAliasType(
    "GenerateLinkUserOauthURLRequestDtoContext",
    Union[GenerateLinkUserOauthURLRequestDtoContext2, str],
)


class GenerateLinkUserOauthURLRequestDtoTypedDict(TypedDict):
    subscriber_id: str
    r"""The subscriber ID to link to their chat identity. Required — this operation always binds a specific subscriber to a user identity in the chat provider."""
    integration_identifier: str
    r"""Integration identifier"""
    connection_identifier: NotRequired[str]
    r"""Identifier of the existing channel connection to associate this user endpoint with. Generated automatically if not provided."""
    context: NotRequired[Dict[str, GenerateLinkUserOauthURLRequestDtoContextTypedDict]]
    user_scope: NotRequired[List[str]]
    r"""**Slack only**: User-level OAuth scopes for \"Sign in with Slack\". Defaults to: identity.basic. **MS Teams**: ignored — uses delegated OpenID scopes (openid, profile, User.Read)."""


class GenerateLinkUserOauthURLRequestDto(BaseModel):
    subscriber_id: Annotated[str, pydantic.Field(alias="subscriberId")]
    r"""The subscriber ID to link to their chat identity. Required — this operation always binds a specific subscriber to a user identity in the chat provider."""

    integration_identifier: Annotated[
        str, pydantic.Field(alias="integrationIdentifier")
    ]
    r"""Integration identifier"""

    connection_identifier: Annotated[
        Optional[str], pydantic.Field(alias="connectionIdentifier")
    ] = None
    r"""Identifier of the existing channel connection to associate this user endpoint with. Generated automatically if not provided."""

    context: Optional[Dict[str, GenerateLinkUserOauthURLRequestDtoContext]] = None

    user_scope: Annotated[Optional[List[str]], pydantic.Field(alias="userScope")] = None
    r"""**Slack only**: User-level OAuth scopes for \"Sign in with Slack\". Defaults to: identity.basic. **MS Teams**: ignored — uses delegated OpenID scopes (openid, profile, User.Read)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["connectionIdentifier", "context", "userScope"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GenerateLinkUserOauthURLRequestDto.model_rebuild()
except NameError:
    pass
