"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .requestlogresponsedto import RequestLogResponseDto, RequestLogResponseDtoTypedDict
from novu_py.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRequestsResponseDtoTypedDict(TypedDict):
    data: List[RequestLogResponseDtoTypedDict]
    r"""Request log data"""
    total: float
    r"""Total number of requests"""
    page_size: NotRequired[float]
    r"""Page size"""
    page: NotRequired[float]
    r"""Current page number"""


class GetRequestsResponseDto(BaseModel):
    data: List[RequestLogResponseDto]
    r"""Request log data"""

    total: float
    r"""Total number of requests"""

    page_size: Annotated[Optional[float], pydantic.Field(alias="pageSize")] = None
    r"""Page size"""

    page: Optional[float] = None
    r"""Current page number"""
