"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
import pydantic
from typing import Any, Dict
from typing_extensions import Annotated, TypedDict


class GetSubscriberNotificationsCountResponseDtoTypedDict(TypedDict):
    count: float
    r"""The count of notifications matching the filter"""
    filter_: Dict[str, Any]
    r"""The filter applied"""


class GetSubscriberNotificationsCountResponseDto(BaseModel):
    count: float
    r"""The count of notifications matching the filter"""

    filter_: Annotated[Dict[str, Any], pydantic.Field(alias="filter")]
    r"""The filter applied"""


try:
    GetSubscriberNotificationsCountResponseDto.model_rebuild()
except NameError:
    pass
