"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
from typing_extensions import TypedDict


class HTTPRequestKeyValuePairDtoTypedDict(TypedDict):
    key: str
    r"""Key of the key-value pair"""
    value: str
    r"""Value of the key-value pair"""


class HTTPRequestKeyValuePairDto(BaseModel):
    key: str
    r"""Key of the key-value pair"""

    value: str
    r"""Value of the key-value pair"""
