"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class LineUserEndpointDtoTypedDict(TypedDict):
    user_id: str
    r"""LINE user ID"""


class LineUserEndpointDto(BaseModel):
    user_id: Annotated[str, pydantic.Field(alias="userId")]
    r"""LINE user ID"""


try:
    LineUserEndpointDto.model_rebuild()
except NameError:
    pass
