"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentintegrationresponsedto import (
    AgentIntegrationResponseDto,
    AgentIntegrationResponseDtoTypedDict,
)
from .planusagedto import PlanUsageDto, PlanUsageDtoTypedDict
from novu_py.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListAgentIntegrationsResponseDtoTypedDict(TypedDict):
    data: List[AgentIntegrationResponseDtoTypedDict]
    r"""List of agent–integration links"""
    next: Nullable[str]
    r"""The cursor for the next page of results, or null if there are no more pages."""
    previous: Nullable[str]
    r"""The cursor for the previous page of results, or null if this is the first page."""
    total_count: float
    r"""The total count of items (up to 50,000)"""
    total_count_capped: bool
    r"""Whether there are more than 50,000 results available"""
    plan_usage: NotRequired[PlanUsageDtoTypedDict]
    r"""Cloud only. Connected channel usage in this environment against the organization plan limit. Channels connected beyond the limit are flagged with `exceedsPlanLimit` and will not respond to inbound messages."""


class ListAgentIntegrationsResponseDto(BaseModel):
    data: List[AgentIntegrationResponseDto]
    r"""List of agent–integration links"""

    next: Nullable[str]
    r"""The cursor for the next page of results, or null if there are no more pages."""

    previous: Nullable[str]
    r"""The cursor for the previous page of results, or null if this is the first page."""

    total_count: Annotated[float, pydantic.Field(alias="totalCount")]
    r"""The total count of items (up to 50,000)"""

    total_count_capped: Annotated[bool, pydantic.Field(alias="totalCountCapped")]
    r"""Whether there are more than 50,000 results available"""

    plan_usage: Annotated[Optional[PlanUsageDto], pydantic.Field(alias="planUsage")] = (
        None
    )
    r"""Cloud only. Connected channel usage in this environment against the organization plan limit. Channels connected beyond the limit are flagged with `exceedsPlanLimit` and will not respond to inbound messages."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["planUsage"])
        nullable_fields = set(["next", "previous"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ListAgentIntegrationsResponseDto.model_rebuild()
except NameError:
    pass
