"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentskillinputdto import AgentSkillInputDto, AgentSkillInputDtoTypedDict
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProviderID(str, Enum):
    ANTHROPIC = "anthropic"
    NOVU_ANTHROPIC = "novu-anthropic"
    ANTHROPIC_AWS = "anthropic-aws"


class ManagedRuntimeDtoTypedDict(TypedDict):
    provider_id: ProviderID
    integration_id: str
    r"""ID of an existing Novu integration (kind: \"agent\") that holds the provider API key and provisioned environment. Create the integration first via POST /integrations."""
    external_agent_id: NotRequired[str]
    r"""ID of an existing agent on the provider platform. When set, Novu adopts the agent instead of creating a new one."""
    external_environment_id: NotRequired[str]
    r"""ID of an existing environment on the provider platform. When set, Novu adopts the environment."""
    model: NotRequired[str]
    system_prompt: NotRequired[str]
    tools: NotRequired[List[str]]
    mcp_servers: NotRequired[List[str]]
    skills: NotRequired[List[AgentSkillInputDtoTypedDict]]


class ManagedRuntimeDto(BaseModel):
    provider_id: Annotated[ProviderID, pydantic.Field(alias="providerId")]

    integration_id: Annotated[str, pydantic.Field(alias="integrationId")]
    r"""ID of an existing Novu integration (kind: \"agent\") that holds the provider API key and provisioned environment. Create the integration first via POST /integrations."""

    external_agent_id: Annotated[
        Optional[str], pydantic.Field(alias="externalAgentId")
    ] = None
    r"""ID of an existing agent on the provider platform. When set, Novu adopts the agent instead of creating a new one."""

    external_environment_id: Annotated[
        Optional[str], pydantic.Field(alias="externalEnvironmentId")
    ] = None
    r"""ID of an existing environment on the provider platform. When set, Novu adopts the environment."""

    model: Optional[str] = None

    system_prompt: Annotated[Optional[str], pydantic.Field(alias="systemPrompt")] = None

    tools: Optional[List[str]] = None

    mcp_servers: Annotated[Optional[List[str]], pydantic.Field(alias="mcpServers")] = (
        None
    )

    skills: Optional[List[AgentSkillInputDto]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "externalAgentId",
                "externalEnvironmentId",
                "model",
                "systemPrompt",
                "tools",
                "mcpServers",
                "skills",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ManagedRuntimeDto.model_rebuild()
except NameError:
    pass
