"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .buttontypeenum import ButtonTypeEnum
from novu_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class MessageActionResultTypedDict(TypedDict):
    payload: NotRequired[Dict[str, Any]]
    r"""Payload of the action result"""
    type: NotRequired[ButtonTypeEnum]
    r"""Type of button for the action result"""


class MessageActionResult(BaseModel):
    payload: Optional[Dict[str, Any]] = None
    r"""Payload of the action result"""

    type: Optional[ButtonTypeEnum] = None
    r"""Type of button for the action result"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["payload", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
