"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
from novu_py.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MessagesControllerDeleteMessagesByTransactionIDQueryParamChannel(str, Enum):
    r"""The channel of the message to be deleted"""

    IN_APP = "in_app"
    EMAIL = "email"
    SMS = "sms"
    CHAT = "chat"
    PUSH = "push"


class MessagesControllerDeleteMessagesByTransactionIDRequestTypedDict(TypedDict):
    transaction_id: str
    channel: NotRequired[
        MessagesControllerDeleteMessagesByTransactionIDQueryParamChannel
    ]
    r"""The channel of the message to be deleted"""
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class MessagesControllerDeleteMessagesByTransactionIDRequest(BaseModel):
    transaction_id: Annotated[
        str,
        pydantic.Field(alias="transactionId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    channel: Annotated[
        Optional[MessagesControllerDeleteMessagesByTransactionIDQueryParamChannel],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The channel of the message to be deleted"""

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel", "idempotency-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MessagesControllerDeleteMessagesByTransactionIDResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class MessagesControllerDeleteMessagesByTransactionIDResponse(BaseModel):
    headers: Dict[str, List[str]]
