"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
from typing_extensions import TypedDict


class PlanUsageDtoTypedDict(TypedDict):
    used: float
    r"""Current usage count for the resource in this environment."""
    limit: float
    r"""Amount included in the organization plan."""


class PlanUsageDto(BaseModel):
    used: float
    r"""Current usage count for the resource in this environment."""

    limit: float
    r"""Amount included in the organization plan."""
