"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscriberresponsedtooptional import (
    SubscriberResponseDtoOptional,
    SubscriberResponseDtoOptionalTypedDict,
)
from novu_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


class PreviewPayloadDtoContext2TypedDict(TypedDict):
    r"""Rich context object with id and optional data"""

    id: str
    data: NotRequired[Dict[str, Any]]
    r"""Optional additional context data"""


class PreviewPayloadDtoContext2(BaseModel):
    r"""Rich context object with id and optional data"""

    id: str

    data: Optional[Dict[str, Any]] = None
    r"""Optional additional context data"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


PreviewPayloadDtoContextTypedDict = TypeAliasType(
    "PreviewPayloadDtoContextTypedDict", Union[PreviewPayloadDtoContext2TypedDict, str]
)


PreviewPayloadDtoContext = TypeAliasType(
    "PreviewPayloadDtoContext", Union[PreviewPayloadDtoContext2, str]
)


class PreviewPayloadDtoTypedDict(TypedDict):
    subscriber: NotRequired[SubscriberResponseDtoOptionalTypedDict]
    r"""Partial subscriber information"""
    payload: NotRequired[Dict[str, Any]]
    r"""Payload data"""
    steps: NotRequired[Dict[str, Any]]
    r"""Steps data"""
    context: NotRequired[Dict[str, PreviewPayloadDtoContextTypedDict]]


class PreviewPayloadDto(BaseModel):
    subscriber: Optional[SubscriberResponseDtoOptional] = None
    r"""Partial subscriber information"""

    payload: Optional[Dict[str, Any]] = None
    r"""Payload data"""

    steps: Optional[Dict[str, Any]] = None
    r"""Steps data"""

    context: Optional[Dict[str, PreviewPayloadDtoContext]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["subscriber", "payload", "steps", "context"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
