"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Target(str, Enum):
    r"""Target window for the redirection."""

    SELF = "_self"
    BLANK = "_blank"
    PARENT = "_parent"
    TOP = "_top"
    UNFENCED_TOP = "_unfencedTop"


class RedirectDtoTypedDict(TypedDict):
    url: NotRequired[str]
    r"""URL for redirection. Must be a valid URL or start with / or {{ variable }}."""
    target: NotRequired[Target]
    r"""Target window for the redirection."""


class RedirectDto(BaseModel):
    url: Optional[str] = None
    r"""URL for redirection. Must be a valid URL or start with / or {{ variable }}."""

    target: Optional[Target] = Target.SELF
    r"""Target window for the redirection."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["url", "target"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
