"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class TransactionIDTypedDict(TypedDict):
    r"""Transaction identifier"""


class TransactionID(BaseModel):
    r"""Transaction identifier"""


class RequestLogResponseDtoTypedDict(TypedDict):
    id: str
    r"""Request log identifier"""
    created_at: str
    r"""Creation timestamp"""
    url: str
    r"""Request URL"""
    url_pattern: str
    r"""URL pattern"""
    method: str
    r"""HTTP method"""
    status_code: float
    r"""HTTP status code"""
    path: str
    r"""Request path"""
    hostname: str
    r"""Request hostname"""
    ip: str
    r"""Client IP address"""
    user_agent: str
    r"""User agent string"""
    request_body: str
    r"""Request body"""
    response_body: str
    r"""Response body"""
    user_id: str
    r"""User identifier"""
    organization_id: str
    r"""Organization identifier"""
    environment_id: str
    r"""Environment identifier"""
    auth_type: str
    r"""Authentication type"""
    duration_ms: float
    r"""Request duration in milliseconds"""
    transaction_id: NotRequired[Nullable[TransactionIDTypedDict]]
    r"""Transaction identifier"""


class RequestLogResponseDto(BaseModel):
    id: str
    r"""Request log identifier"""

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]
    r"""Creation timestamp"""

    url: str
    r"""Request URL"""

    url_pattern: Annotated[str, pydantic.Field(alias="urlPattern")]
    r"""URL pattern"""

    method: str
    r"""HTTP method"""

    status_code: Annotated[float, pydantic.Field(alias="statusCode")]
    r"""HTTP status code"""

    path: str
    r"""Request path"""

    hostname: str
    r"""Request hostname"""

    ip: str
    r"""Client IP address"""

    user_agent: Annotated[str, pydantic.Field(alias="userAgent")]
    r"""User agent string"""

    request_body: Annotated[str, pydantic.Field(alias="requestBody")]
    r"""Request body"""

    response_body: Annotated[str, pydantic.Field(alias="responseBody")]
    r"""Response body"""

    user_id: Annotated[str, pydantic.Field(alias="userId")]
    r"""User identifier"""

    organization_id: Annotated[str, pydantic.Field(alias="organizationId")]
    r"""Organization identifier"""

    environment_id: Annotated[str, pydantic.Field(alias="environmentId")]
    r"""Environment identifier"""

    auth_type: Annotated[str, pydantic.Field(alias="authType")]
    r"""Authentication type"""

    duration_ms: Annotated[float, pydantic.Field(alias="durationMs")]
    r"""Request duration in milliseconds"""

    transaction_id: Annotated[
        OptionalNullable[TransactionID], pydantic.Field(alias="transactionId")
    ] = UNSET
    r"""Transaction identifier"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["transactionId"]
        nullable_fields = ["transactionId"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
