"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dependencyreasonenum import DependencyReasonEnum
from .resourcetypeenum import ResourceTypeEnum
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ResourceDependencyDtoTypedDict(TypedDict):
    resource_type: ResourceTypeEnum
    r"""Type of the layout"""
    resource_id: str
    r"""ID of the dependent resource"""
    resource_name: str
    r"""Name of the dependent resource"""
    is_blocking: bool
    r"""Whether this dependency blocks the operation"""
    reason: DependencyReasonEnum
    r"""Reason for the dependency"""


class ResourceDependencyDto(BaseModel):
    resource_type: Annotated[ResourceTypeEnum, pydantic.Field(alias="resourceType")]
    r"""Type of the layout"""

    resource_id: Annotated[str, pydantic.Field(alias="resourceId")]
    r"""ID of the dependent resource"""

    resource_name: Annotated[str, pydantic.Field(alias="resourceName")]
    r"""Name of the dependent resource"""

    is_blocking: Annotated[bool, pydantic.Field(alias="isBlocking")]
    r"""Whether this dependency blocks the operation"""

    reason: DependencyReasonEnum
    r"""Reason for the dependency"""


try:
    ResourceDependencyDto.model_rebuild()
except NameError:
    pass
