"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .integrationissueenum import IntegrationIssueEnum
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StepIntegrationIssueTypedDict(TypedDict):
    issue_type: IntegrationIssueEnum
    r"""Type of integration issue"""
    message: str
    r"""Detailed message describing the issue"""
    variable_name: NotRequired[str]
    r"""Name of the variable related to the issue"""


class StepIntegrationIssue(BaseModel):
    issue_type: Annotated[IntegrationIssueEnum, pydantic.Field(alias="issueType")]
    r"""Type of integration issue"""

    message: str
    r"""Detailed message describing the issue"""

    variable_name: Annotated[Optional[str], pydantic.Field(alias="variableName")] = None
    r"""Name of the variable related to the issue"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["variableName"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
