"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .marksubscribernotificationsasseendto import (
    MarkSubscriberNotificationsAsSeenDto,
    MarkSubscriberNotificationsAsSeenDtoTypedDict,
)
from novu_py.types import BaseModel, UNSET_SENTINEL
from novu_py.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SubscribersControllerMarkNotificationsAsSeenRequestTypedDict(TypedDict):
    subscriber_id: str
    r"""The identifier of the subscriber"""
    mark_subscriber_notifications_as_seen_dto: (
        MarkSubscriberNotificationsAsSeenDtoTypedDict
    )
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class SubscribersControllerMarkNotificationsAsSeenRequest(BaseModel):
    subscriber_id: Annotated[
        str,
        pydantic.Field(alias="subscriberId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The identifier of the subscriber"""

    mark_subscriber_notifications_as_seen_dto: Annotated[
        MarkSubscriberNotificationsAsSeenDto,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["idempotency-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SubscribersControllerMarkNotificationsAsSeenResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]


class SubscribersControllerMarkNotificationsAsSeenResponse(BaseModel):
    headers: Dict[str, List[str]]
