"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inboxnotificationdto import InboxNotificationDto, InboxNotificationDtoTypedDict
from enum import Enum
from novu_py.types import BaseModel, UNSET_SENTINEL
from novu_py.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ActionType(str, Enum):
    r"""The type of action (primary or secondary)"""

    PRIMARY = "primary"
    SECONDARY = "secondary"


class SubscribersControllerCompleteNotificationActionRequestTypedDict(TypedDict):
    subscriber_id: str
    r"""The identifier of the subscriber"""
    notification_id: str
    r"""The identifier of the notification"""
    action_type: ActionType
    r"""The type of action (primary or secondary)"""
    context_keys: NotRequired[List[str]]
    r"""Context keys for filtering"""
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class SubscribersControllerCompleteNotificationActionRequest(BaseModel):
    subscriber_id: Annotated[
        str,
        pydantic.Field(alias="subscriberId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The identifier of the subscriber"""

    notification_id: Annotated[
        str,
        pydantic.Field(alias="notificationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The identifier of the notification"""

    action_type: Annotated[
        ActionType,
        pydantic.Field(alias="actionType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The type of action (primary or secondary)"""

    context_keys: Annotated[
        Optional[List[str]],
        pydantic.Field(alias="contextKeys"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Context keys for filtering"""

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contextKeys", "idempotency-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SubscribersControllerCompleteNotificationActionResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: InboxNotificationDtoTypedDict


class SubscribersControllerCompleteNotificationActionResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: InboxNotificationDto
