"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class TelegramChatEndpointDtoTypedDict(TypedDict):
    chat_id: str
    r"""Telegram chat ID"""


class TelegramChatEndpointDto(BaseModel):
    chat_id: Annotated[str, pydantic.Field(alias="chatId")]
    r"""Telegram chat ID"""


try:
    TelegramChatEndpointDto.model_rebuild()
except NameError:
    pass
