"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .steptypeenum import StepTypeEnum
from .throttlecontroldto import ThrottleControlDto, ThrottleControlDtoTypedDict
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ThrottleStepUpsertDtoControlValuesTypedDict = TypeAliasType(
    "ThrottleStepUpsertDtoControlValuesTypedDict",
    Union[ThrottleControlDtoTypedDict, Dict[str, Any]],
)
r"""Control values for the Throttle step."""


ThrottleStepUpsertDtoControlValues = TypeAliasType(
    "ThrottleStepUpsertDtoControlValues", Union[ThrottleControlDto, Dict[str, Any]]
)
r"""Control values for the Throttle step."""


class ThrottleStepUpsertDtoTypedDict(TypedDict):
    name: str
    r"""Name of the step"""
    type: StepTypeEnum
    r"""Type of the step"""
    id: NotRequired[str]
    r"""Database identifier of the step. Used for updating the step."""
    step_id: NotRequired[str]
    r"""Unique identifier for the step"""
    control_values: NotRequired[ThrottleStepUpsertDtoControlValuesTypedDict]
    r"""Control values for the Throttle step."""


class ThrottleStepUpsertDto(BaseModel):
    name: str
    r"""Name of the step"""

    type: StepTypeEnum
    r"""Type of the step"""

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = None
    r"""Database identifier of the step. Used for updating the step."""

    step_id: Annotated[Optional[str], pydantic.Field(alias="stepId")] = None
    r"""Unique identifier for the step"""

    control_values: Annotated[
        Optional[ThrottleStepUpsertDtoControlValues],
        pydantic.Field(alias="controlValues"),
    ] = None
    r"""Control values for the Throttle step."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["_id", "stepId", "controlValues"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ThrottleStepUpsertDto.model_rebuild()
except NameError:
    pass
