"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolApprovalRequestPayloadDtoTypedDict(TypedDict):
    approval_id: str
    r"""Unique id for this approval request (matches the AI SDK approvalId)."""
    tool_call_id: str
    r"""Id of the tool call awaiting approval."""
    name: str
    r"""Name of the gated tool."""
    input: NotRequired[Dict[str, Any]]
    r"""Tool input the model proposed."""
    approve_action_id: NotRequired[str]
    r"""Server-minted approve action id. When omitted, self-hosted tool-approval:* is minted at persist."""
    deny_action_id: NotRequired[str]
    r"""Server-minted deny action id. When omitted, self-hosted tool-approval:* is minted at persist."""
    mcp_server_name: NotRequired[str]
    r"""MCP server name when the gated tool is from an MCP server (for UI labels)."""


class ToolApprovalRequestPayloadDto(BaseModel):
    approval_id: Annotated[str, pydantic.Field(alias="approvalId")]
    r"""Unique id for this approval request (matches the AI SDK approvalId)."""

    tool_call_id: Annotated[str, pydantic.Field(alias="toolCallId")]
    r"""Id of the tool call awaiting approval."""

    name: str
    r"""Name of the gated tool."""

    input: Optional[Dict[str, Any]] = None
    r"""Tool input the model proposed."""

    approve_action_id: Annotated[
        Optional[str], pydantic.Field(alias="approveActionId")
    ] = None
    r"""Server-minted approve action id. When omitted, self-hosted tool-approval:* is minted at persist."""

    deny_action_id: Annotated[Optional[str], pydantic.Field(alias="denyActionId")] = (
        None
    )
    r"""Server-minted deny action id. When omitted, self-hosted tool-approval:* is minted at persist."""

    mcp_server_name: Annotated[Optional[str], pydantic.Field(alias="mcpServerName")] = (
        None
    )
    r"""MCP server name when the gated tool is from an MCP server (for UI labels)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["input", "approveActionId", "denyActionId", "mcpServerName"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ToolApprovalRequestPayloadDto.model_rebuild()
except NameError:
    pass
