"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAgentBridgeRequestDtoTypedDict(TypedDict):
    bridge_url: NotRequired[str]
    r"""Production bridge URL for this agent"""
    dev_bridge_url: NotRequired[str]
    r"""Development bridge URL (set by npx novu dev)"""
    dev_bridge_active: NotRequired[bool]
    r"""Whether the dev bridge override is active"""


class UpdateAgentBridgeRequestDto(BaseModel):
    bridge_url: Annotated[Optional[str], pydantic.Field(alias="bridgeUrl")] = None
    r"""Production bridge URL for this agent"""

    dev_bridge_url: Annotated[Optional[str], pydantic.Field(alias="devBridgeUrl")] = (
        None
    )
    r"""Development bridge URL (set by npx novu dev)"""

    dev_bridge_active: Annotated[
        Optional[bool], pydantic.Field(alias="devBridgeActive")
    ] = None
    r"""Whether the dev bridge override is active"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bridgeUrl", "devBridgeUrl", "devBridgeActive"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    UpdateAgentBridgeRequestDto.model_rebuild()
except NameError:
    pass
