"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TagsTypedDict(TypedDict):
    r"""Filter notifications by workflow tags (OR for string[], or { and: [{ or: string[] }, ...] } for AND of OR-groups)."""


class Tags(BaseModel):
    r"""Filter notifications by workflow tags (OR for string[], or { and: [{ or: string[] }, ...] } for AND of OR-groups)."""


class UpdateAllSubscriberNotificationsDtoTypedDict(TypedDict):
    tags: NotRequired[TagsTypedDict]
    r"""Filter notifications by workflow tags (OR for string[], or { and: [{ or: string[] }, ...] } for AND of OR-groups)."""
    data: NotRequired[str]
    r"""Filter notifications by data attributes (JSON string)"""
    context_keys: NotRequired[List[str]]
    r"""Context keys for filtering notifications"""


class UpdateAllSubscriberNotificationsDto(BaseModel):
    tags: Optional[Tags] = None
    r"""Filter notifications by workflow tags (OR for string[], or { and: [{ or: string[] }, ...] } for AND of OR-groups)."""

    data: Optional[str] = None
    r"""Filter notifications by data attributes (JSON string)"""

    context_keys: Annotated[
        Optional[List[str]], pydantic.Field(alias="contextKeys")
    ] = None
    r"""Context keys for filtering notifications"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tags", "data", "contextKeys"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    UpdateAllSubscriberNotificationsDto.model_rebuild()
except NameError:
    pass
