"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class UpdateDomainDtoTypedDict(TypedDict):
    data: NotRequired[Dict[str, str]]
    r"""Replaces domain metadata when provided (max 10 keys, 500 characters total for keys+values)."""


class UpdateDomainDto(BaseModel):
    data: Optional[Dict[str, str]] = None
    r"""Replaces domain metadata when provided (max 10 keys, 500 characters total for keys+values)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
