"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WebexRoomEndpointDtoTypedDict(TypedDict):
    room_id: str
    r"""Webex room ID"""
    parent_id: NotRequired[str]
    r"""Optional Webex parent message ID for threaded replies"""


class WebexRoomEndpointDto(BaseModel):
    room_id: Annotated[str, pydantic.Field(alias="roomId")]
    r"""Webex room ID"""

    parent_id: Annotated[Optional[str], pydantic.Field(alias="parentId")] = None
    r"""Optional Webex parent message ID for threaded replies"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["parentId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WebexRoomEndpointDto.model_rebuild()
except NameError:
    pass
