"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from novu_py.types import BaseModel
from novu_py.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class WorkflowControllerGetWorkflowRequestTypedDict(TypedDict):
    workflow_id: str
    environment_id: str
    idempotency_key: NotRequired[str]
    r"""A header for idempotency purposes"""


class WorkflowControllerGetWorkflowRequest(BaseModel):
    workflow_id: Annotated[
        str,
        pydantic.Field(alias="workflowId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    environment_id: Annotated[
        str,
        pydantic.Field(alias="environmentId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="idempotency-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A header for idempotency purposes"""


class WorkflowControllerGetWorkflowResponseBodyTypedDict(TypedDict):
    pass


class WorkflowControllerGetWorkflowResponseBody(BaseModel):
    pass


class WorkflowControllerGetWorkflowResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: WorkflowControllerGetWorkflowResponseBodyTypedDict


class WorkflowControllerGetWorkflowResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: WorkflowControllerGetWorkflowResponseBody
