workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    novu-OAS:
        inputs:
            - location: https://api.novu.co/openapi.sdk.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/novu/novu/novu-oas
targets:
    novu:
        target: python
        source: novu-OAS
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/novu/novu/novu-oas-python-code-samples
            blocking: false
